knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        google_main:
            # this will be one of the supported types
            type: google
            client_id: '%env(GOOGLE_ID)%'
            client_secret: '%env(GOOGLE_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_google_check
            redirect_params: {}
            # Décommenter la ligne suivante pour permettre l'authentification dans la doc de l'API
            use_state: false