nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: |
                API for enterprises to access the BileMo smartphone catalogue.

                To use "Smartphones" and "Your clients" routes, you must provide the following header:

                    Authorization : bearer a87e020B...

                To get your token, use the "getToken" route.

            version: 1.0.0
            contact:
                name: API Support
                email: support@example.com
                url: http://example.com/support
        components:
            securitySchemes:
                # OAuth2:
                #     type: oauth2
                #     description: This API uses the Google OAuth 2.0 server to get an access token.
                #     flows:
                #       authorizationCode:
                #         authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
                #         tokenUrl: https://www.googleapis.com/oauth2/v4/token
                #         scopes:
                #           'email': 'Allow to retrieve user email'                       '                       
                bearerAuth:
                    type: http
                    description: This API uses an access token to authenticate users.
                    scheme: bearer
                    bearerFormat: JWT
            responses:
              Unauthorized:
                description: "Unauthorized - See examples for possible messages"
                content:
                  application/json:
                    schema:
                      oneOf:
                        - ref: "#/components/schemas/MissingToken"
                        - ref: "#/components/schemas/ExpiredToken"
                    examples:
                      MissingToken:
                        summary: MissingToken
                        value:
                          code: 401
                          message: Full authentication is required to access this resource.
                      ExpiredToken:
                        summary: ExpiredToken
                        value:
                          code: 401
                          message: Your access token is not valid :(
            schemas:
              MissingToken:
                type: object
                properties:
                  code:
                    type: integer
                    const: 401
                  message:
                    type: string
                    const: "Full authentication is required to access this resource."
              ExpiredToken:
                type: object
                properties:
                  code:
                    type: integer
                    const: 401
                  message:
                    type: string
                    const: "Your access token is not valid :("                       


    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/phone\.*
            - ^/client\.*
            - ^/getToken
