nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: API destinée aux entreprises souhaitant accéder au catalogue de smartphones de BileMo
            version: 1.0.0
        components:
            securitySchemes:
                OAuth2:
                    type: oauth2
                    description: This API uses Google's OAuth 2.0 server to authenticate users.
                    flows:
                      authorizationCode:
                        authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
                        tokenUrl: https://www.googleapis.com/oauth2/v4/token
                        scopes:
                          'email': 'Allow to retrieve user email'                       
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/phone\.*
            - ^/client\.*
